development:
  app_url_en: 'https://bacicos.codica.la'
  app_url_ru: 'https://bacicos.codica.la'

production:
  app_url_en: 'https://bacicos.codica.la'
  app_url_ru: 'https://bacicos.codica.la'

test:
  app_url_en: 'https://bacicos.codica.la'
  app_url_ru: 'https://bacicos.codica.la'

